### ISSUE TITLE
换svg貌似不行？

### ISSUE THREAD

**Issue by ArtisanM** [callmesoul/wechat-miniprogram-rate-plugin#1]
是我svg的格式问题吗？给svg属性赋值的时候各种报错，svg我是从设计给的蓝湖上下载的

**Comment by ArtisanM** [comment]
[star.svg.zip](https://github.com/callmesoul/wechat-miniprogram-rate-plugin/files/6448071/star.svg.zip)

**Comment by callmesoul** [comment]
@ArtisanM 可以参考下示例，是要传svg文件的代码哦，且尽量不换行，不是传文件地址哦，因为组件之间传不了文件
